language: generic
sudo: required
dist: trusty

os:
  - linux

env:
  global:
    - DISPLAY=:99.0

before_install:
  - Xvfb $DISPLAY &
  - wget https://netix.dl.sourceforge.net/project/lazarus/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.8.4/fpc-src_3.0.4-2_amd64.deb  
  - wget https://kent.dl.sourceforge.net/project/lazarus/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.8.4/fpc_3.0.4-3_amd64.deb
  - wget https://netix.dl.sourceforge.net/project/lazarus/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.8.4/lazarus-project_1.8.4-0_amd64.deb
install:
  - sudo dpkg -i fpc_3.0.4-3_amd64.deb
  - sudo dpkg -i fpc-src_3.0.4-2_amd64.deb
  - sudo dpkg -i lazarus-project_1.8.4-0_amd64.deb
  
script:
  - lazbuild pck/paxjson_package.lpk
  - lazbuild pck/tests.lpr
  - lazbuild demo/pck/jsonDemo.lpr
  - ls -1 bin/*
  - ./bin/test/x86_64/tests -a --format=plain

notifications:
  email:
    on_success: false
    on_failure: change
